### ISSUE TITLE
Explorer should be deployed in staging mode

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-local-dev#3]
The explorer deployed to [staging](https://explorer-silk.now.sh/transactions) seems to have the dropdown on the top right side to select the network. In production, this is disabled. The explorer deployment type should be updated, so the network can be set to the mocknet as part of this image.

this will help https://github.com/blockstack/docs/pull/827

**Comment by wileyj** [comment]
This won't be possible without a stable/updated image being available. 
Currently, the image being used for the explorer is `quay.io/blockstack/explorer:latest` - i'm hesitant to update that to a feature branch etc, since those branches can't be counted on to be maintained. 

The explorer launching as part of this process is using defined Env Vars:
https://github.com/blockstack/stacks-local-dev/blob/master/.env#L93-L95

So unless the explorer is written to not use these vars, it should only be showing data related to a local mocknet.

**Comment by agraebe** [comment]
discussed this in discord. not a priority - the dropdown will only help resolve a minor caching issue (if the network was set on a locally deployed instance before the image would be used)
